name: ebrew
description: "A comprehensive Flutter coffee shop app with device capabilities."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # Device Capabilities
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  camera: ^0.10.6
  sensors_plus: ^5.0.1
  connectivity_plus: ^6.0.3
  
  # UI & Utils
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/


